"""
Refactored SESAR data loader with improved architecture.
Key improvements:
- Class-based structure instead of global variables
- Proper batch processing
- Better error handling
- Configuration management
- Separated concerns
Generated by claude-code based on SMR sesar_samples.py 2025-12-09
Reads postgres SESAR db (version 202504), generates duckDB table with parquet structure.
This is a parquet design that Dave Vieglais set up origiinally, with s, p, o links in
otype '_edge_'.
Rows have an 'otype' that determines what columns must or may have values
row_id is used os the key to link parent objects to child objects that are values
    for some properties.
This code hasn't been tested and debugged.
superseded by SESAR2/standalone/sesar_to_parquet.py
SMR 2025-12-11
"""
import io
import json
import psycopg2
import hashlib
from shapely import wkt
import logging
import sys
import csv
from typing import Dict, List, Optional, Any, Tuple
from dataclasses import dataclass
from contextlib import contextmanager
import pickle
import numbers
from datetime import datetime, timedelta
import time
import pathlib

# Import your existing modules
from __init__ import *
from pqg.common import *
from pqg.pqg_singletable import *

logger = logging.getLogger('sesarParquet')


# ============================================================================
# Configuration
# ============================================================================

@dataclass
class SESARConfig:
    """Configuration for SESAR data loading."""
    # Database connection
    db_name: str = "SESAR202504"
    db_user: str = "postgres"
    db_password: str = "smrpostgis"
    db_host: str = "127.0.0.1"
    db_port: int = 5432

    # DuckDB settings
    duckdb_path: str = "sesarduck8.ddb"

    # Processing settings
    batch_size: int = 10000
    write_batch_size: int = 50000

    # Update settings
    is_update: bool = False
    update_window_days: int = 60

    # Cache files
    cache_dir: str = "cache"

    # Output
    output_parquet: str = "sesarParq9"
    temp_json_file: str = "temp_batch.json"
    temp_csv_file: str = "temp_batch.csv"


# ============================================================================
# Constants
# ============================================================================

# Table abbreviations
ABBREVIATIONS = {
    'individual': 'ind',
    'institution': 'ins',
    'material_type': 'mat',
    'sample': 'sam',
    'locality': 'loc',
    'initiative': 'ini',
    'relation': 'rel',
    'platform': 'pla',
}

# Vocabulary configurations
VOCAB_CONFIGS = [
    ['affiliation_type', 'aft', '', 'label', 'SESAR Affiliation Type', '', 'affiliation_type_id'],
    ['agent_role_type', 'art', '', 'label', 'SESAR agent roles', '', 'agent_role_id'],
    ['country', 'cty', '', 'label', 'ISO3166 country', '', 'country_id'],
    ['geologic_time_scale', 'gts', 'geologic_time_interval_uri', 'label', 'ICS 2020 Chronostratigraphic', 'scheme_uri',
     'geologic_time_id'],
    ['initiative_type', 'ini', '', 'label', 'SESAR Initiative Type', '', 'initiative_type_id'],
    ['institution_type', 'ins', '', 'label', 'SESAR Institution Type', '', 'institution_type_id'],
    ['launch_type', 'lat', '', 'label', 'SESAR Launch Type', '', 'launch_type_id'],
    ['location_method', 'lom', '', 'label', 'SESAR Location Method', '', 'location_method_id'],
    ['material_role_type', 'mar', '', 'label', 'SESAR Material Role', '', 'material_role_id'],
    ['platform', 'pla', '', 'label', 'SESAR Platform', '', 'platform_id'],
    ['platform_type', 'plt', '', 'label', 'SESAR Platform Type', '', 'platform_type_id'],
    ['relation_type', 'rel', '', 'label', 'SESAR relation Type', 'scheme_uri', 'relation_type_id'],
    ['resource_type', 'ret', 'resource_type_uri', 'label', 'SESAR Resource Type', 'scheme_uri', 'resource_type_id'],
    ['sample_type', 'sat', 'sample_type_uri', 'label', 'SESAR Sample Type', 'scheme_uri', 'sample_type_id'],
    ['sampled_feature_type', 'sft', 'feature_type_uri', 'label', 'SESAR Sampled Feature Type', 'scheme_uri',
     'feature_type_id'],
    ['sampling_method', 'sam', 'method_uri', 'label', 'SESAR Sampling Method', 'scheme_uri', 'collection_method_id'],
    ['sesar_spatial_ref_sys', 'ssr', 'identifier', 'name', 'SESAR Spatial Reference Systems', '', 'spatial_ref_id'],
]

# ============================================================================
# Batch Processor (from previous artifact)
# ============================================================================

from enum import Enum


class FlushStrategy(Enum):
    SIZE = "size"
    TIME = "time"
    HYBRID = "hybrid"


@dataclass
class BatchStats:
    items_processed: int = 0
    items_failed: int = 0
    batches_flushed: int = 0
    total_flush_time: float = 0.0
    start_time: float = time.time()

    @property
    def elapsed_time(self) -> float:
        return time.time() - self.start_time

    @property
    def items_per_second(self) -> float:
        elapsed = self.elapsed_time
        return self.items_processed / elapsed if elapsed > 0 else 0.0


class BatchProcessor:
    def __init__(
            self,
            batch_size: int = 1000,
            flush_callback=None,
            strategy: FlushStrategy = FlushStrategy.SIZE,
            max_retries: int = 3,
    ):
        self.batch_size = batch_size
        self.flush_callback = flush_callback
        self.strategy = strategy
        self.max_retries = max_retries

        self._batch: List[Dict[str, Any]] = []
        self._last_flush_time = time.time()
        self.stats = BatchStats()

    def add(self, item: Dict[str, Any]) -> None:
        try:
            self._batch.append(item)
            self.stats.items_processed += 1

            if len(self._batch) >= self.batch_size:
                self.flush()

        except Exception as e:
            self.stats.items_failed += 1
            logger.error(f"Error adding item to batch: {e}", exc_info=True)

    def flush(self) -> None:
        if not self._batch or not self.flush_callback:
            return

        flush_start = time.time()
        retry_count = 0

        while retry_count <= self.max_retries:
            try:
                self.flush_callback(self._batch)
                self.stats.batches_flushed += 1
                self.stats.total_flush_time += time.time() - flush_start
                self._last_flush_time = time.time()
                self._batch.clear()
                logger.info(f"Batch flushed. Stats: {self.stats.items_processed} processed, "
                            f"{self.stats.items_per_second:.2f} items/sec")
                break

            except Exception as e:
                retry_count += 1
                logger.error(f"Error flushing batch (attempt {retry_count}/{self.max_retries}): {e}")

                if retry_count > self.max_retries:
                    logger.error(f"Max retries exceeded. Losing {len(self._batch)} items!")
                    self.stats.items_failed += len(self._batch)
                    self._batch.clear()
                    raise
                else:
                    time.sleep(2 ** retry_count)

    def finalize(self) -> BatchStats:
        if self._batch:
            self.flush()
        return self.stats

    @contextmanager
    def processing_context(self):
        try:
            yield self
        finally:
            self.finalize()


# ============================================================================
# Database Manager
# ============================================================================

class DatabaseManager:
    """Manages database connections and operations."""

    def __init__(self, config: SESARConfig):
        self.config = config
        self._sesar_conn = None
        self._duck_conn = None
        self._graph = None

    @contextmanager
    def sesar_connection(self):
        """Context manager for SESAR PostgreSQL connection."""
        try:
            logger.info(f'set up db connection: {self.config.db_name}')
            conn = psycopg2.connect(
                database=self.config.db_name,
                user=self.config.db_user,
                password=self.config.db_password,
                host=self.config.db_host,
                port=self.config.db_port,
            )
            yield conn
        except Exception as e:
            logger.error(f'SESAR database connection failed: {e}')
            raise
        finally:
            if conn:
                conn.close()

    def get_duckdb_graph(self):
        """Get or create DuckDB graph connection."""
        if self._duck_conn is None:
            import duckdb
            self._duck_conn = duckdb.connect(self.config.duckdb_path)
            self._graph = createGraph(self._duck_conn)
        return self._graph

    def execute_query(self, conn, query: str) -> List[Tuple]:
        """Execute query and return results."""
        with conn.cursor() as cursor:
            cursor.execute(query)
            return cursor.fetchall()

    def get_fields(self, conn, table_name: str) -> List[str]:
        """Get field names for a table."""
        query = """
                SELECT column_name
                FROM information_schema.columns
                WHERE table_schema = 'public' \
                  AND table_name = %s
                ORDER BY ordinal_position \
                """
        try:
            results = self.execute_query(conn, query % f"'{table_name}'")
            return [row[0] for row in results]
        except Exception as e:
            logger.error(f"Error getting fields for {table_name}: {e}")
            return []

    def close(self):
        """Close all connections."""
        if self._duck_conn:
            self._duck_conn.close()


# ============================================================================
# Cache Manager
# ============================================================================

class CacheManager:
    """Manages pickle cache files for lookups."""

    def __init__(self, cache_dir: str = "cache"):
        self.cache_dir = pathlib.Path(cache_dir)
        self.cache_dir.mkdir(exist_ok=True)

    def get_cache_path(self, name: str) -> pathlib.Path:
        return self.cache_dir / f"{name}.pkl"

    def load_or_create(self, name: str, create_func) -> Optional[Dict]:
        """Load from cache or create new."""
        cache_path = self.get_cache_path(name)
        print ("load cache from", cache_path)
        try:
            if cache_path.exists():
                with open(cache_path, 'rb') as f:
                    data = pickle.load(f)
                    logger.info(f"Loaded {name} from cache")
                    return data
        except Exception as e:
            logger.warning(f"Failed to load cache {name}: {e}")

        # Create new
        try:
            data = create_func()
            if data:
                with open(cache_path, 'wb') as f:
                    pickle.dump(data, f)
                logger.info(f"Created and cached {name}")
                return data
            else:
                logger.error(f"Failed to create {name}")
                return None
        except Exception as e:
            logger.error(f"Error creating {name}: {e}")
            return None


# ============================================================================
# SESAR Data Loader
# ============================================================================

class SESARDataLoader:
    """Main class for loading SESAR data."""

    def __init__(self, config: SESARConfig):
        self.config = config
        self.db_manager = DatabaseManager(config)
        self.cache_manager = CacheManager(config.cache_dir)

        # Lookups
        self.concept_lkup: Dict = {}
        self.agent_lkup: Dict = {}
        self.sesar_user_lkup: Dict = {}
        self.init_lkup: Dict = {}
        self.collector_lkup: Dict = {}
        self.archive_lkup: Dict = {}
        self.locality_lkup: Dict = {}
        self.addname_lkup: Dict = {}
        self.relres_lkup: Dict = {}

        # Template for inserts
        self.insert_template: Dict = {}

        # Batch processor
        self.batch_processor = None

    def initialize(self):
        """Initialize the loader."""
        logger.info("Initializing SESAR Data Loader")

        # Get graph and initialize template
        graph = self.db_manager.get_duckdb_graph()
        self._initialize_insert_template(graph)

        # Setup batch processor
        self._setup_batch_processor(graph)

    def _initialize_insert_template(self, graph):
        """Initialize the insert template from database schema."""
        query = "DESCRIBE node;"
        with graph.getCursor() as cursor:
            cursor.execute(query)
            data = cursor.fetchall()

        for item in data:
            self.insert_template[item[0]] = None

        logger.info(f"Insert template initialized with {len(self.insert_template)} fields")

    def _setup_batch_processor(self, graph):
        """Setup the batch processor with flush callback."""

        def flush_to_duckdb(batch: List[Dict[str, Any]]):
            """Flush batch to DuckDB."""
            # Filter out records without PIDs
            valid_batch = [r for r in batch if r.get('pid')]

            if not valid_batch:
                return

            # Write to JSON
            with open(self.config.temp_json_file, 'w') as f:
                for record in valid_batch:
                    json.dump(record, f)
                    f.write('\n')

            # Insert into database
            sql = f"INSERT OR IGNORE INTO node SELECT * FROM read_ndjson('{self.config.temp_json_file}');"
            with graph.getCursor() as cursor:
                cursor.execute(sql)
            graph._connection.commit()

        self.batch_processor = BatchProcessor(
            batch_size=self.config.write_batch_size,
            flush_callback=flush_to_duckdb,
            strategy=FlushStrategy.SIZE,
        )

    def get_blank_insert(self) -> Dict[str, Any]:
        """Get a blank insert dictionary."""
        return dict.fromkeys(self.insert_template, None)

    def set_value(self, insert_dict: Dict, field: str, value: Any) -> None:
        """Set value in insert dictionary, handling tuples."""
        insert_dict[field] = value[0] if isinstance(value, tuple) else value

    # ========================================================================
    # Vocabulary Loading
    # ========================================================================

    def load_vocabularies(self):
        """Load all vocabularies."""
        logger.info("Loading vocabularies")

        with self.db_manager.sesar_connection() as conn:
            for vocab_config in VOCAB_CONFIGS:
                self._load_concept_vocabulary(conn, vocab_config)

            # Load material types (special case)
            self._load_material_types(conn)

        logger.info(f"Loaded {len(self.concept_lkup)} concepts")

    def _load_concept_vocabulary(self, conn, config: List):
        """Load a single vocabulary table."""
        table_name, abbrev, uri_field, label_field, scheme_name, scheme_uri_field, id_field = config

        try:
            query = f"SELECT * FROM {table_name}"
            data = self.db_manager.execute_query(conn, query)
            fields = self.db_manager.get_fields(conn, table_name)

            for row in data:
                obj = dict(zip(fields, row))

                # Determine PID
                if uri_field and obj.get(uri_field):
                    pid = obj[uri_field]
                else:
                    pid = f"urn:local:{abbrev}.{obj[id_field]}"

                # Determine scheme URI
                scheme_uri = obj.get(scheme_uri_field) if scheme_uri_field else ''

                # Create concept
                concept = IdentifiedConcept(
                    pid=pid,
                    label=obj[label_field],
                    scheme_name=scheme_name,
                    scheme_uri=scheme_uri,
                    altids=[f"{abbrev}.{obj[id_field]}"]
                )

                lookup_key = f"{abbrev}.{obj[id_field]}"
                self.concept_lkup[lookup_key] = {'flag': False, 'obj': concept}

            logger.info(f"Loaded vocabulary: {table_name}")

        except Exception as e:
            logger.error(f"Error loading vocabulary {table_name}: {e}")

    def _load_material_types(self, conn):
        """Load material types (special handling)."""
        try:
            query = """
                    SELECT material_type.material_type_id, \
                           material_type.label,
                           scheme_uri, \
                           material_type_uri
                    FROM material_type
                             JOIN sample ON material_type_id = general_material_type_id
                    UNION
                    SELECT material_type.material_type_id, \
                           material_type.label,
                           scheme_uri, \
                           material_type_uri
                    FROM material_type
                             JOIN sample_material ON material_type.material_type_id = sample_material.material_type_id \
                    """

            data = self.db_manager.execute_query(conn, query)

            for row in data:
                mat_id, label, scheme_uri, mat_uri = row

                pid = mat_uri if mat_uri else f"urn:local:mat.{mat_id}"

                concept = IdentifiedConcept(
                    pid=pid,
                    label=label,
                    scheme_name="SESAR Material Type",
                    scheme_uri=scheme_uri or '',
                    altids=[f"mat.{mat_id}"]
                )

                self.concept_lkup[f"mat.{mat_id}"] = {'flag': False, 'obj': concept}

            logger.info("Loaded material types")

        except Exception as e:
            logger.error(f"Error loading material types: {e}")

    # ========================================================================
    # Agent Loading
    # ========================================================================

    def load_agents(self):
        """Load all agents (individuals and institutions)."""
        logger.info("Loading agents")

        with self.db_manager.sesar_connection() as conn:
            self._load_individuals(conn)
            self._load_institutions(conn)

        logger.info(f"Loaded {len(self.agent_lkup)} agents")

    def _load_individuals(self, conn):
        """Load individuals into agent lookup."""
        try:
            query = "SELECT * FROM individual"
            data = self.db_manager.execute_query(conn, query)
            fields = self.db_manager.get_fields(conn, 'individual')

            for row in data:
                obj = dict(zip(fields, row))

                # Determine label
                label = (obj.get('label') or obj.get('individual_uri') or
                         obj.get('description') or obj.get('email'))

                if not label:
                    continue

                # Determine PID
                pid = obj.get('individual_uri') or f"urn:local:ind.{obj['individual_id']}"

                # Build contact info
                contact_parts = []
                if obj.get('address'):
                    contact_parts.append(obj['address'])
                if obj.get('email'):
                    contact_parts.append(obj['email'])
                if obj.get('phone'):
                    contact_parts.append(f"Phone: {obj['phone']}")

                agent = Agent(
                    pid=pid,
                    affiliation=None,
                    contact_information=", ".join(contact_parts),
                    name=label,
                    role='',
                    altids=[f"ind.{obj['individual_id']}"]
                )

                self.agent_lkup[f"ind.{obj['individual_id']}"] = {
                    'flag': False,
                    'obj': agent
                }

            logger.info("Loaded individuals")

        except Exception as e:
            logger.error(f"Error loading individuals: {e}")

    def _load_institutions(self, conn):
        """Load institutions into agent lookup."""
        try:
            query = "SELECT * FROM institution"
            data = self.db_manager.execute_query(conn, query)
            fields = self.db_manager.get_fields(conn, 'institution')

            for row in data:
                obj = dict(zip(fields, row))

                # Determine label
                label = (obj.get('label') or obj.get('description') or
                         obj.get('email'))

                if not label:
                    continue

                pid = f"urn:local:ins.{obj['institution_id']}"

                # Build contact info
                contact_parts = []
                if obj.get('address'):
                    contact_parts.append(obj['address'])
                if obj.get('email'):
                    contact_parts.append(obj['email'])

                agent = Agent(
                    pid=pid,
                    affiliation=None,
                    contact_information=", ".join(contact_parts),
                    name=label,
                    role='',
                    altids=[f"ins.{obj['institution_id']}"]
                )

                self.agent_lkup[f"ins.{obj['institution_id']}"] = {
                    'flag': False,
                    'obj': agent
                }

            logger.info("Loaded institutions")

        except Exception as e:
            logger.error(f"Error loading institutions: {e}")

    # ========================================================================
    # Supporting Lookups
    # ========================================================================

    def load_supporting_lookups(self):
        """Load all supporting lookup tables."""
        logger.info("Loading supporting lookups")

        with self.db_manager.sesar_connection() as conn:
            self.sesar_user_lkup = self._load_sesar_users(conn)
            self.init_lkup = self._load_initiatives(conn)
            self.collector_lkup = self._load_collectors(conn)
            self.archive_lkup = self._load_archives(conn)
            self.locality_lkup = self._load_localities(conn)
            self.addname_lkup = self._load_additional_names(conn)
            self.relres_lkup = self._load_related_resources(conn)

    def _load_sesar_users(self, conn) -> Dict:
        """Load SESAR user lookup."""
        try:
            query = "SELECT * FROM sesar_user"
            data = self.db_manager.execute_query(conn, query)
            fields = self.db_manager.get_fields(conn, 'sesar_user')

            lookup = {}
            for row in data:
                obj = dict(zip(fields, row))

                if obj.get('individual_id'):
                    lookup[str(obj['sesar_user_id'])] = f"ind.{obj['individual_id']}"
                elif obj.get('institution_id'):
                    lookup[str(obj['sesar_user_id'])] = f"ins.{obj['institution_id']}"

            logger.info(f"Loaded {len(lookup)} SESAR users")
            return lookup

        except Exception as e:
            logger.error(f"Error loading SESAR users: {e}")
            return {}

    def _load_initiatives(self, conn) -> Dict:
        """Load initiatives lookup."""
        try:
            query = "SELECT * FROM initiative"
            data = self.db_manager.execute_query(conn, query)
            fields = self.db_manager.get_fields(conn, 'initiative')

            lookup = {}
            for row in data:
                obj = dict(zip(fields, row))

                label_parts = []
                if obj.get('label'):
                    label_parts.append(obj['label'])
                if obj.get('initiative_uri'):
                    label_parts.append(f"URI--{obj['initiative_uri']}")
                if obj.get('description'):
                    label_parts.append(obj['description'])
                if obj.get('funding'):
                    label_parts.append(f"Funding--{obj['funding']}")

                pid = f"urn:local:ini.{obj['initiative_id']}"
                lookup[pid] = "; ".join(label_parts)

            logger.info(f"Loaded {len(lookup)} initiatives")
            return lookup

        except Exception as e:
            logger.error(f"Error loading initiatives: {e}")
            return {}

    def _load_collectors(self, conn) -> Dict:
        """Load collector relationships."""
        try:
            query = """
                    SELECT * \
                    FROM related_sample_agent
                    WHERE relation_type_id = 1
                    ORDER BY sample_id \
                    """
            data = self.db_manager.execute_query(conn, query)
            fields = self.db_manager.get_fields(conn, 'related_sample_agent')

            lookup = {}
            for row in data:
                obj = dict(zip(fields, row))

                key = f"sam.{obj['sample_id']}"

                if obj['agent_type'] == 'Individual':
                    val = f"ind.{obj['individual_id']}"
                elif obj['agent_type'] == 'Institution':
                    val = f"ins.{obj['institution_id']}"
                else:
                    continue

                if key not in lookup:
                    lookup[key] = []
                lookup[key].append(val)

            logger.info(f"Loaded collectors for {len(lookup)} samples")
            return lookup

        except Exception as e:
            logger.error(f"Error loading collectors: {e}")
            return {}

    def _load_archives(self, conn) -> Dict:
        """Load archive relationships."""
        try:
            query = """
                    SELECT * \
                    FROM related_sample_agent
                    WHERE relation_type_id = 3
                    ORDER BY sample_id \
                    """
            data = self.db_manager.execute_query(conn, query)
            fields = self.db_manager.get_fields(conn, 'related_sample_agent')

            lookup = {}
            for row in data:
                obj = dict(zip(fields, row))

                key = f"sam.{obj['sample_id']}"
                ind = f"ind.{obj['individual_id']}" if obj['agent_type'] == 'Individual' else None
                ins = f"ins.{obj['institution_id']}" if obj['agent_type'] == 'Institution' else None

                lookup[key] = [ind, ins]

            logger.info(f"Loaded archives for {len(lookup)} samples")
            return lookup

        except Exception as e:
            logger.error(f"Error loading archives: {e}")
            return {}

    def _load_localities(self, conn) -> Dict:
        """Load localities."""
        try:
            query = "SELECT * FROM locality"
            data = self.db_manager.execute_query(conn, query)
            fields = self.db_manager.get_fields(conn, 'locality')

            lookup = {}
            for row in data:
                obj = dict(zip(fields, row))
                lookup[f"loc.{obj['locality_id']}"] = obj

            logger.info(f"Loaded {len(lookup)} localities")
            return lookup

        except Exception as e:
            logger.error(f"Error loading localities: {e}")
            return {}

    def _load_additional_names(self, conn) -> Dict:
        """Load additional sample names."""
        try:
            query = "SELECT * FROM sample_additional_name"
            data = self.db_manager.execute_query(conn, query)
            fields = self.db_manager.get_fields(conn, 'sample_additional_name')

            lookup = {}
            for row in data:
                obj = dict(zip(fields, row))

                key = str(obj['sample_id'])
                name = obj.get('name')

                if key and name:
                    if key not in lookup:
                        lookup[key] = []
                    lookup[key].append(name)

            logger.info(f"Loaded additional names for {len(lookup)} samples")
            return lookup

        except Exception as e:
            logger.error(f"Error loading additional names: {e}")
            return {}

    def _load_related_resources(self, conn) -> Dict:
        """Load related resources."""
        try:
            query = "SELECT * FROM related_resource"
            data = self.db_manager.execute_query(conn, query)
            fields = self.db_manager.get_fields(conn, 'related_resource')

            lookup = {}
            for row in data:
                obj = dict(zip(fields, row))

                if not obj.get('sample_id'):
                    continue

                relation = SampleRelation(
                    pid=f"rel.{obj['relation_id']}",
                    target=obj['related_resource_uri'],
                    description='',
                    label=f"child of {obj['related_resource_uri']}",
                    relationship='has parent material sample'
                )

                key = str(obj['sample_id'])
                if key not in lookup:
                    lookup[key] = []
                lookup[key].append(relation)

            logger.info(f"Loaded related resources for {len(lookup)} samples")
            return lookup

        except Exception as e:
            logger.error(f"Error loading related resources: {e}")
            return {}

    # ========================================================================
    # Helper Methods for Adding Records
    # ========================================================================

    def add_concept(self, concept: IdentifiedConcept):
        """Add a concept to the batch."""
        insert_val = self.get_blank_insert()
        self.set_value(insert_val, 'otype', 'IdentifiedConcept')
        insert_val['pid'] = concept['pid']
        insert_val['label'] = concept['label']
        insert_val['scheme_name'] = concept['scheme_name']
        insert_val['scheme_uri'] = concept['scheme_uri']
        insert_val['altids'] = concept['altids']
        self.batch_processor.add(insert_val)

    def add_agent(self, agent: Agent):
        """Add an agent to the batch."""
        insert_val = self.get_blank_insert()
        self.set_value(insert_val, 'otype', 'Agent')
        insert_val['pid'] = agent['pid']
        insert_val['affiliation'] = agent['affiliation']
        insert_val['contact_information'] = agent['contact_information']
        insert_val['name'] = agent['name']
        insert_val['role'] = agent['role']
        insert_val['altids'] = agent['altids']
        self.batch_processor.add(insert_val)


    def get_edge_pid(self, s: str, p: str, o: str, n: Optional[str] = None) -> str:
        """Generate edge PID from subject, predicate, object."""
        try:
            h = hashlib.md5()
            h.update(s.encode("utf-8"))
            h.update(p.encode("utf-8"))
            h.update(o.encode("utf-8"))
            if n is not None:
                h.update(n.encode("utf-8"))
            return f"anon_{h.hexdigest()}"
        except Exception as e:
            logger.error(f"Error generating edge PID: {e}")
            return None


    def add_edge(self, s: str, p: str, o: str, n: Optional[str] = None):
        """Add an edge to the batch."""
        edge_pid = self.get_edge_pid(s, p, o, n)
        if not edge_pid:
            return

        insert_val = self.get_blank_insert()
        self.set_value(insert_val, 'otype', '_edge_')
        insert_val['pid'] = edge_pid
        insert_val['s'] = s
        insert_val['p'] = p
        insert_val['o'] = o
        insert_val['n'] = n
        self.batch_processor.add(insert_val)


    # ========================================================================
    # Geospatial and Location Processing
    # ========================================================================

    def create_geospatial_location(self, sample_obj: Dict) -> Optional[GeospatialCoordLocation]:
        """Create geospatial coordinate location from sample data."""
        lat = sample_obj.get('latitude')
        lon = sample_obj.get('longitude')
        elev = sample_obj.get('elevation')
        depth_min = sample_obj.get('depth_min')
        depth_max = sample_obj.get('depth_max')

        # Check if we have any location data
        if not any([lat, lon, elev, depth_min, depth_max]):
            return None

        # Build vertical position string
        vert_parts = []
        if elev is not None:
            vert_parts.append(str(elev))
            if sample_obj.get('elevation_uom'):
                vert_parts.append(f"UOM: {sample_obj['elevation_uom']}")

        if depth_min is not None or depth_max is not None:
            if depth_min == depth_max:
                vert_parts.append(f"Depth: {depth_min}")
            elif depth_min and depth_max:
                vert_parts.append(f"Depth range: {depth_min} to {depth_max}")
            elif depth_min:
                vert_parts.append(f"Depth minimum: {depth_min}")
            elif depth_max:
                vert_parts.append(f"Depth maximum: {depth_max}")

            if sample_obj.get('depth_uom'):
                vert_parts.append(f"UOM: {sample_obj['depth_uom']}")

        vertical_pos = " ".join(vert_parts) if vert_parts else None

        # Create geometry if we have coordinates
        geometry = None
        if isinstance(lat, numbers.Number) and isinstance(lon, numbers.Number):
            try:
                point_wkt = f"POINT({lat} {lon})"
                geometry = str(wkt.loads(point_wkt))
            except Exception as e:
                logger.warning(f"Failed to create geometry for sample {sample_obj.get('sample_id')}: {e}")

        # Create location record
        pid = f"urn:local:geo.{sample_obj['sample_id']}"

        insert_val = self.get_blank_insert()
        self.set_value(insert_val, 'otype', 'GeospatialCoordLocation')
        insert_val['pid'] = pid
        insert_val['latitude'] = str(lat) if lat is not None else None
        insert_val['longitude'] = str(lon) if lon is not None else None
        insert_val['obfuscated'] = False
        insert_val['elevation'] = vertical_pos
        insert_val['geometry'] = geometry
        self.batch_processor.add(insert_val)

        return GeospatialCoordLocation(
            pid=pid,
            latitude=str(lat) if lat is not None else None,
            longitude=str(lon) if lon is not None else None,
            obfuscated=False,
            elevation=vertical_pos
        )


    def create_sampling_site(self, sample_obj: Dict) -> Optional[SamplingSite]:
        """Create sampling site from sample data."""
        site_pid = f"urn:local:sst.{sample_obj['sample_id']}"

        # Build description
        desc_parts = []
        if sample_obj.get('locality_detail'):
            desc_parts.append(sample_obj['locality_detail'])

        if sample_obj.get('latitude_end'):
            desc_parts.append(
                f"Sampling from lat, long {sample_obj.get('latitude')}, "
                f"{sample_obj.get('longitude')} to {sample_obj['latitude_end']}, "
                f"{sample_obj.get('longitude_end')}"
            )

        if sample_obj.get('location_qualifier'):
            desc_parts.append(sample_obj['location_qualifier'])

        description = ". ".join(desc_parts) if desc_parts else None

        # Get place names from locality
        place_names = []
        loc_name = None

        try:
            locality_key = f"loc.{sample_obj['locality_id']}"
            if locality_key in self.locality_lkup:
                locality = self.locality_lkup[locality_key]

                for field in ['province', 'county', 'city']:
                    if locality.get(field):
                        place_names.append(locality[field])

                if locality.get('country_id'):
                    country_key = f"cty.{locality['country_id']}"
                    if country_key in self.concept_lkup:
                        place_names.append(self.concept_lkup[country_key]['obj']['label'])

                loc_name = locality.get('name')
        except Exception as e:
            logger.debug(f"Error getting locality info: {e}")

        # Create site record
        insert_val = self.get_blank_insert()
        self.set_value(insert_val, 'otype', 'SamplingSite')
        insert_val['pid'] = site_pid
        insert_val['description'] = description
        insert_val['label'] = loc_name
        insert_val['place_name'] = place_names if place_names else None
        insert_val['is_part_of'] = None
        self.batch_processor.add(insert_val)

        return SamplingSite(
            pid=site_pid,
            description=description,
            label=loc_name,
            place_name=place_names,
            site_location=None,
            is_part_of=None
        )


    # ========================================================================
    # Sampling Event Processing
    # ========================================================================

    def create_sampling_event(self, sample_obj: Dict) -> Optional[SamplingEvent]:
        """Create sampling event from sample data."""
        event_pid = f"urn:local:evt.{sample_obj['sample_id']}"

        # Build collection description
        desc_parts = []

        # Collection method
        if sample_obj.get('collection_method_id'):
            method_key = f"sam.{sample_obj['collection_method_id']}"
            if method_key in self.concept_lkup:
                concept = self.concept_lkup[method_key]['obj']
                if not self.concept_lkup[method_key]['flag']:
                    self.add_concept(concept)
                    self.concept_lkup[method_key]['flag'] = True
                desc_parts.append(f"method:{concept['label']}; pid:{concept['pid']}")

        if sample_obj.get('collection_method_detail'):
            desc_parts.append(sample_obj['collection_method_detail'])

        # Platform
        if sample_obj.get('platform_id'):
            platform_key = f"pla.{sample_obj['platform_id']}"
            if platform_key in self.concept_lkup:
                concept = self.concept_lkup[platform_key]['obj']
                if not self.concept_lkup[platform_key]['flag']:
                    self.add_concept(concept)
                    self.concept_lkup[platform_key]['flag'] = True
                desc_parts.append(f"Platform: {concept['label']}; pid:{concept['pid']}")

        # Launch platform
        if sample_obj.get('launch_platform_id'):
            launch_key = f"pla.{sample_obj['launch_platform_id']}"
            if launch_key in self.concept_lkup:
                concept = self.concept_lkup[launch_key]['obj']
                if not self.concept_lkup[launch_key]['flag']:
                    self.add_concept(concept)
                    self.concept_lkup[launch_key]['flag'] = True
                desc_parts.append(f"Launch Platform: {concept['label']}; pid:{concept['pid']}")

        if sample_obj.get('launch_label'):
            desc_parts.append(f"Launch: {sample_obj['launch_label']}")

        collection_desc = "; ".join(desc_parts) if desc_parts else None

        # Get sampled feature type (context category)
        context_category = None
        if sample_obj.get('sampled_feature_type_id'):
            sft_key = f"sft.{sample_obj['sampled_feature_type_id']}"
            if sft_key in self.concept_lkup:
                concept = self.concept_lkup[sft_key]['obj']
                if not self.concept_lkup[sft_key]['flag']:
                    self.add_concept(concept)
                    self.concept_lkup[sft_key]['flag'] = True
                context_category = concept

        # Get collectors
        collectors = []
        collector_key = f"sam.{sample_obj['sample_id']}"
        if collector_key in self.collector_lkup:
            for collector_id in self.collector_lkup[collector_key]:
                if collector_id in self.agent_lkup:
                    agent = self.agent_lkup[collector_id]['obj']
                    self.agent_lkup[collector_id]['role'] = 'collector'
                    collectors.append(agent)

                    if not self.agent_lkup[collector_id]['flag']:
                        self.add_agent(agent)
                        self.agent_lkup[collector_id]['flag'] = True

        # Get locality name
        locality_name = None
        loc_key = f"loc.{sample_obj.get('locality_id')}"
        if loc_key in self.locality_lkup:
            locality_name = self.locality_lkup[loc_key].get('label')

        # Build time string
        time_str = None
        start_date = sample_obj.get('collection_start_date')
        end_date = sample_obj.get('collection_end_date')

        if start_date and end_date:
            time_str = f"{start_date}/{end_date}"
        elif start_date:
            time_str = str(start_date)
        elif end_date:
            time_str = str(end_date)

        # Get project/initiative
        project = None
        if sample_obj.get('cruise_field_prgrm_id'):
            init_key = f"urn:local:ini.{sample_obj['cruise_field_prgrm_id']}"
            if init_key in self.init_lkup:
                project = self.init_lkup[init_key]

        # Build label
        label_parts = []
        if project:
            label_parts.append(project)

        if sample_obj.get('launch_label'):
            label_parts.append(sample_obj['launch_label'])
        elif sample_obj.get('name'):
            label_parts.append(f"Collection of sample {sample_obj['name']}")
        else:
            label_parts.append("Collection of sample")

        if time_str:
            label_parts.append(time_str)

        label = "; ".join(label_parts)

        # Create sampling event record
        insert_val = self.get_blank_insert()
        self.set_value(insert_val, 'otype', 'SamplingEvent')
        insert_val['pid'] = event_pid
        insert_val['description'] = collection_desc
        insert_val['authorized_by'] = None
        insert_val['has_feature_of_interest'] = locality_name
        insert_val['label'] = label
        insert_val['project'] = project
        insert_val['result_time'] = time_str
        self.batch_processor.add(insert_val)

        # Create and link geospatial location
        geo_location = self.create_geospatial_location(sample_obj)
        if geo_location:
            self.add_edge(event_pid, 'sample_location', geo_location['pid'])

        # Create and link sampling site
        sampling_site = self.create_sampling_site(sample_obj)
        if sampling_site:
            self.add_edge(event_pid, 'sampling_site', sampling_site['pid'])

        # Link collectors
        for collector in collectors:
            self.add_edge(event_pid, 'responsibility', collector['pid'])

        # Link context category
        if context_category:
            self.add_edge(event_pid, 'has_context_category', context_category['pid'])

        return SamplingEvent(
            pid=event_pid,
            description=collection_desc,
            authorized_by=None,
            has_context_category=context_category,
            has_feature_of_interest=locality_name,
            label=label,
            project=project,
            responsibility=collectors,
            result_time=time_str,
            sample_location=geo_location,
            sampling_site=sampling_site
        )


    # ========================================================================
    # Curation Processing
    # ========================================================================

    def create_curation(self, sample_obj: Dict) -> Optional[MaterialSampleCuration]:
        """Create material sample curation record."""
        if not sample_obj.get('cur_owner_id'):
            return None

        owner_key = str(sample_obj['cur_owner_id'])
        if owner_key not in self.sesar_user_lkup:
            return None

        agent_key = self.sesar_user_lkup[owner_key]
        if agent_key not in self.agent_lkup:
            return None

        owner = self.agent_lkup[agent_key]['obj']
        owner['role'] = 'owner'

        if not self.agent_lkup[agent_key]['flag']:
            self.add_agent(owner)
            self.agent_lkup[agent_key]['flag'] = True

        curation_pid = f"urn:local:cur.{sample_obj['sample_id']}"

        # Create curation record
        insert_val = self.get_blank_insert()
        self.set_value(insert_val, 'otype', 'MaterialSampleCuration')
        insert_val['pid'] = curation_pid
        insert_val['label'] = owner['name']
        insert_val['description'] = 'current owner'
        insert_val['access_constraints'] = []
        self.batch_processor.add(insert_val)

        # Link owner to curation
        self.add_edge(curation_pid, 'responsibility', owner['pid'])

        return MaterialSampleCuration(
            pid=curation_pid,
            responsibility=owner,
            label=owner['name'],
            description='current owner',
            access_constraints=[]
        )


    # ========================================================================
    # Sample Processing
    # ========================================================================

    def process_sample(self, sample_obj: Dict):
        """Process a single sample record."""
        sample_id = sample_obj['sample_id']
        sample_pid = f"sam.{sample_id}"

        # Get registrant
        registrant = None
        if sample_obj.get('cur_registrant_id'):
            reg_key = str(sample_obj['cur_registrant_id'])
            if reg_key in self.sesar_user_lkup:
                agent_key = self.sesar_user_lkup[reg_key]
                if agent_key in self.agent_lkup:
                    registrant = self.agent_lkup[agent_key]['obj']
                    registrant['role'] = 'registrant'

                    if not self.agent_lkup[agent_key]['flag']:
                        self.add_agent(registrant)
                        self.agent_lkup[agent_key]['flag'] = True

        # Build description
        desc_parts = []
        if sample_obj.get('sample_description'):
            desc_parts.append(sample_obj['sample_description'])

        if sample_obj.get('material_name_verbatim'):
            desc_parts.append(f"Material: {sample_obj['material_name_verbatim']}")

        if sample_obj.get('size'):
            desc_parts.append(f"Sample size: {sample_obj['size']}")

        if sample_obj.get('latitude') and sample_obj.get('latitude_end'):
            desc_parts.append(
                f"Latitude from {sample_obj['latitude']} to {sample_obj['latitude_end']}"
            )

        if sample_obj.get('longitude') and sample_obj.get('longitude_end'):
            desc_parts.append(
                f"Longitude from {sample_obj['longitude']} to {sample_obj['longitude_end']}"
            )

        if sample_obj.get('geologic_age_verbatim'):
            desc_parts.append(f"Age: {sample_obj['geologic_age_verbatim']}")

        # Numeric ages
        age_min = sample_obj.get('numeric_age_min')
        age_max = sample_obj.get('numeric_age_max')

        if age_min and age_max:
            desc_parts.append(f"Age between {age_min} and {age_max}")
        elif age_min:
            desc_parts.append(f"Minimum age {age_min}")
        elif age_max:
            desc_parts.append(f"Maximum age {age_max}")

        if sample_obj.get('numeric_age_unit'):
            desc_parts.append(f"Age units {sample_obj['numeric_age_unit']}")

        if sample_obj.get('age_qualifier'):
            desc_parts.append(f"Age qualifier: {sample_obj['age_qualifier']}")

        description = ". ".join(desc_parts) if desc_parts else None

        # Build keywords
        keywords = []

        if sample_obj.get('geologic_unit'):
            geo_concept = IdentifiedConcept(
                pid=f"geo_unit.{sample_id}",
                label=sample_obj['geologic_unit'],
                scheme_name="Geologic Unit",
                scheme_uri=None
            )
            keywords.append(geo_concept)
            self.add_concept(geo_concept)

        # Geologic age older
        if sample_obj.get('geologic_age_older_id'):
            older_key = f"gts.{sample_obj['geologic_age_older_id']}"
            if older_key in self.concept_lkup:
                concept = self.concept_lkup[older_key]['obj']
                if not self.concept_lkup[older_key]['flag']:
                    self.add_concept(concept)
                    self.concept_lkup[older_key]['flag'] = True
                keywords.append(concept)

        # Geologic age younger
        if sample_obj.get('geologic_age_younger_id'):
            younger_key = f"gts.{sample_obj['geologic_age_younger_id']}"
            if younger_key in self.concept_lkup:
                concept = self.concept_lkup[younger_key]['obj']
                if not self.concept_lkup[younger_key]['flag']:
                    self.add_concept(concept)
                    self.concept_lkup[younger_key]['flag'] = True
                keywords.append(concept)

        # Get additional names
        alt_names = self.addname_lkup.get(str(sample_id))

        # Get related resources
        related_rels = self.relres_lkup.get(str(sample_id))
        if related_rels:
            for rel in related_rels:
                insert_val = self.get_blank_insert()
                self.set_value(insert_val, 'otype', 'SampleRelation')
                insert_val['pid'] = rel['pid']
                insert_val['target'] = rel['target']
                insert_val['description'] = ''
                insert_val['label'] = rel['label']
                insert_val['relationship'] = 'has parent material sample'
                self.batch_processor.add(insert_val)

        # Get category concepts
        context_cat = None
        if sample_obj.get('sampled_feature_type_id'):
            sft_key = f"sft.{sample_obj['sampled_feature_type_id']}"
            if sft_key in self.concept_lkup:
                context_cat = self.concept_lkup[sft_key]['obj']
                if not self.concept_lkup[sft_key]['flag']:
                    self.add_concept(context_cat)
                    self.concept_lkup[sft_key]['flag'] = True

        material_cat = None
        if sample_obj.get('general_material_type_id'):
            mat_key = f"mat.{sample_obj['general_material_type_id']}"
            if mat_key in self.concept_lkup:
                material_cat = self.concept_lkup[mat_key]['obj']
                if not self.concept_lkup[mat_key]['flag']:
                    self.add_concept(material_cat)
                    self.concept_lkup[mat_key]['flag'] = True

        sample_obj_type = None
        if sample_obj.get('sample_type_id'):
            sat_key = f"sat.{sample_obj['sample_type_id']}"
            if sat_key in self.concept_lkup:
                sample_obj_type = self.concept_lkup[sat_key]['obj']
                if not self.concept_lkup[sat_key]['flag']:
                    self.add_concept(sample_obj_type)
                    self.concept_lkup[sat_key]['flag'] = True

        # Create curation
        curation = self.create_curation(sample_obj)

        # Create sampling event
        sampling_event = self.create_sampling_event(sample_obj)

        # Create material sample record
        insert_val = self.get_blank_insert()
        self.set_value(insert_val, 'otype', 'MaterialSampleRecord')
        insert_val['pid'] = sample_pid
        insert_val['alternate_identifiers'] = alt_names
        insert_val['complies_with'] = None
        insert_val['dc_rights'] = None
        insert_val['description'] = description
        insert_val['label'] = sample_obj.get('name')
        insert_val['last_modified_time'] = str(sample_obj.get('last_update_date', ''))
        insert_val['sample_identifier'] = sample_obj.get('igsn')
        insert_val['sampling_purpose'] = sample_obj.get('purpose')
        self.batch_processor.add(insert_val)

        # Add edges
        if curation:
            self.add_edge(sample_pid, 'curation', curation['pid'])

        if context_cat:
            self.add_edge(sample_pid, 'has_context_category', context_cat['pid'])

        if material_cat:
            self.add_edge(sample_pid, 'has_material_category', material_cat['pid'])

        if sample_obj_type:
            self.add_edge(sample_pid, 'has_sample_object_type', sample_obj_type['pid'])

        for keyword in keywords:
            self.add_edge(sample_pid, 'keywords', keyword['pid'])

        if sampling_event:
            self.add_edge(sample_pid, 'produced_by', sampling_event['pid'])

        if registrant:
            self.add_edge(sample_pid, 'registrant', registrant['pid'])

        if related_rels:
            for rel in related_rels:
                self.add_edge(sample_pid, 'related_resource', rel['pid'])


    def load_samples(self):
        """Load all samples from database."""
        logger.info("Starting sample load")

        with self.db_manager.sesar_connection() as conn:
            # Build query
            where_clause = ""
            if self.config.is_update:
                last_sync = datetime.now().date() - timedelta(days=self.config.update_window_days)
                last_sync_str = last_sync.strftime('%Y-%m-%d 00:00:00')
                where_clause = f"WHERE last_update_date >= '{last_sync_str}'"

            query = f"SELECT * FROM sample {where_clause}"

            # Get fields
            fields = self.db_manager.get_fields(conn, 'sample')

            # Use cursor for batch fetching
            with conn.cursor() as cursor:
                cursor.execute(query)

                samples_processed = 0

                with self.batch_processor.processing_context():
                    while True:
                        # Fetch batch
                        batch = cursor.fetchmany(self.config.batch_size)

                        if not batch:
                            logger.info("No more samples to process")
                            break

                        # Process each sample
                        for row in batch:
                            sample_obj = dict(zip(fields, row))
                            self.process_sample(sample_obj)
                            samples_processed += 1

                        logger.info(f"Processed {samples_processed} samples")

        logger.info(f"Sample load complete. Total: {samples_processed}")


# ========================================================================
# Main Execution
# ========================================================================

    def run(self):
        """Main execution method."""
        start_time = time.time()

        try:
            # Initialize
            self.initialize()

            # Load or create vocabularies
            cached_concepts = self.cache_manager.load_or_create(
                'concept_lkup',
                self.load_vocabularies
            )
            if cached_concepts:
                self.concept_lkup = cached_concepts

            # Load or create agents
            cached_agents = self.cache_manager.load_or_create(
                'agent_lkup',
                self.load_agents
            )
            if cached_agents:
                self.agent_lkup = cached_agents

            # Load supporting lookups
            self.load_supporting_lookups()

            # Load samples
            self.load_samples()

            # Export to Parquet
            if self.config.output_parquet:
                graph = self.db_manager.get_duckdb_graph()
                output_path = pathlib.Path(self.config.output_parquet)
                graph.asParquet(output_path)
                logger.info(f"Exported to Parquet: {output_path}")

            # Print stats
            elapsed = time.time() - start_time
            logger.info(f"Total execution time: {elapsed / 3600:.2f} hours")
            logger.info(f"Batch stats: {self.batch_processor.stats}")

        except Exception as e:
            logger.error(f"Error during execution: {e}", exc_info=True)
            raise
        finally:
            self.db_manager.close()


# ============================================================================
# Main Entry Point
# ============================================================================

def main():
    """Main entry point."""
    # Setup logging
    logging.basicConfig(
        filename='sesar_parquet.log',
        level=logging.INFO,
        format='%(asctime)s - %(name)s - %(levelname)s - %(message)s',
        datefmt='%Y-%m-%d %H:%M:%S'
    )

    # Create configuration
    config = SESARConfig()

    # Create and run loader
    loader = SESARDataLoader(config)
    loader.run()


if __name__ == "__main__":
    main()